const Books = [
  {
    id: 1,
    title: 'Trunk Music',
    category: 'novel',
    author: 'Michael Connelly',
    pubYear: 1997,
    publisher: 'Orion Books',
    image: 'http://i38.photobucket.com/albums/e143/hoxtygen/trunkMusic_zpscbgt86bo.jpg',
  },
  {
    id: 2,
    title: 'Roadside Crosses',
    category: 'novel',
    author: 'Jeffery Deaver',
    pubYear: 2009,
    publisher: 'Pocket Books',
    image: 'http://i38.photobucket.com/albums/e143/hoxtygen/roadside_zpsomimfe1e.jpg',
  },
  {
    id: 3,
    title: 'The Broken Window',
    author: 'Jeffery Deaver',
    category: 'novel',
    pubYear: 2008,
    publisher: 'Pocket Books',
    image: 'http://i38.photobucket.com/albums/e143/hoxtygen/brokenWindow_zpso4w0bdda.jpg',
  },
  {
    id: 4,
    title: 'The Sabbathday River',
    author: 'Jean Hanff Korelitz',
    category: 'novel',
    pubYear: 1990,
    publisher: 'Jove Books',
    image: 'http://i38.photobucket.com/albums/e143/hoxtygen/sabbathDay_zps3zsxhz3z.jpg',
  },
  {
    id: 5,
    title: 'The Poet',
    author: 'Michael Connelly',
    category: 'novel',
    pubYear: 1996,
    publisher: 'Warner Books',
    image: 'http://i38.photobucket.com/albums/e143/hoxtygen/trunkMusic_zpscbgt86bo.jpg',
  },
  {
    id: 6,
    title: 'The Twelfth Card',
    author: 'Jeffery Deaver',
    category: 'novel',
    pubYear: 2005,
    publisher: 'Pocket Books',
    image: 'http://i38.photobucket.com/albums/e143/hoxtygen/twelfthCard_zpsmi1s51wg.jpg',
  },
  {
    id: 7,
    title: 'CSS3 Foundations',
    author: 'Ian Lunn',
    category: 'novel',
    pubYear: 2013,
    publisher: 'John Wiley & Sons Ltd',
    image: 'http://i38.photobucket.com/albums/e143/hoxtygen/twelfthCard_zpsmi1s51wg.jpg',
  },
  {
    id: 8,
    title: 'Hands-On Data Structures and Algorithms with JavaScript',
    author: 'Kashyap Mukkamala',
    category: 'novel',
    pubYear: 2018,
    publisher: 'Packt Publishing Ltd.',
    image: 'http://i38.photobucket.com/albums/e143/hoxtygen/twelfthCard_zpsmi1s51wg.jpg',
  },
];

export default Books;
